/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fábio
 */
import java.util.Random;

public class TelaBiscoito extends javax.swing.JFrame {

    /**
     * Creates new form TelaBiscoito
     */
    public TelaBiscoito() 
    {
        initComponents();
        setSize(887,607);           // Define o tamanho da tela mostra para o usuário 
        setLocationRelativeTo(null); // Centraliza a janela tela 
        setResizable(false);
      bctQuebrado.setVisible(false); // Imagem está invisível 
      lblTitulo.setVisible(false);
     
     
    }
     
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnclick = new javax.swing.JButton();
        lblMensagem = new javax.swing.JLabel();
        bct = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        bctQuebrado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnclick.setBackground(new java.awt.Color(60, 63, 65));
        btnclick.setForeground(new java.awt.Color(255, 255, 255));
        btnclick.setText("QUEBRE O BISCOITO");
        btnclick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclickActionPerformed(evt);
            }
        });
        getContentPane().add(btnclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        lblMensagem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(lblMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 210, 80));

        bct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/biscoito-da-sorte.jpg"))); // NOI18N
        getContentPane().add(bct, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 500, 480));

        lblTitulo.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo.setFont(new java.awt.Font("Segoe UI", 2, 48)); // NOI18N
        lblTitulo.setText("MENSAGEM DO DIA É:");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        bctQuebrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/biscoito-qubrado.JPG"))); // NOI18N
        getContentPane().add(bctQuebrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 200, 940, 450));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 15)); // NOI18N
        jLabel1.setText("BISCOITO CHINES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
           // evento do botão
    private void btnclickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclickActionPerformed
        // TODO add your handling code here:
        bct.setVisible(false);
        bctQuebrado.setVisible(true);
        btnclick.setVisible(false);
        lblTitulo.setVisible(true);
        // Lista de mensagens
        String[] mensagens = {
            "<html> A vida trará coisas boas se tiver paciência.<html>",
            "<html>Não compense na ira o que lhe falta na razão.<html>",
            "<html>A maior de todas as torres começa no solo.<html>",
            "<html>O riso é a menor distância entre duas pessoas.<html>",
            "<html>A maior barreira para o sucesso é o medo do fracasso<html>.",
            "<html>Realize o óbvio, pense no improvável e conquiste o impossível.<html>",
            "<html>Você sempre será a sua melhor companhia!<html>",
            "<html>Você é do tamanho do seu sonho.<html>",
            "<html>Espere pelo mais sábio dos conselhos: o tempo.<html>",
            "<html>A adversidade é um espelho que reflete o verdadeiro eu.<html>"
            
        };
            // Gerando frases aleatórias 
        Random random = new Random();
        int indice = random.nextInt(mensagens.length);
        
        lblMensagem.setText(mensagens[indice]);
    }//GEN-LAST:event_btnclickActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBiscoito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBiscoito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBiscoito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBiscoito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBiscoito().setVisible(true);
            }
        });
    }
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bct;
    private javax.swing.JLabel bctQuebrado;
    private javax.swing.JButton btnclick;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
